class Labeller{
     
    science= {
        biology:[
            'Doctor of Optometry',
            '(DVM) Doctor of Veterinary Medicine',
            'BSc Environmental Sciences',
            'BSc Food Science and Technology',
            'BSc Biochemistry',
            'BSc Biological Science',
        ],
        'elective mathematics':[
            'BSc Actuarial Science',
            'BSc Physics',
            'BSc Statistics',
            'BSc Computer Science',
            'BSc Mathematics'
        ],
        physics:[
            'BSc Meteorology and Climate Science',
            'BSc Physics',
            'BSc Statistics',
            'BSc Computer Science',
            'BSc Mathematics',
            'BSc Actuarial Science'
        ],
        chemistry:[
            'Doctor of Optometry',
            '(DVM) Doctor of Veterinary Medicine',
            'BSc Biochemistry',
            'BSc Biological Science',
            'BSc Environmental Sciences',
            'BSc Food Science and Technology',
            'BSc Meteorology and Climate Science',
            'BSc Physics',
        ],
        'information technology':[
            'BSc Computer Science',
            'BSc Mathematics',
            'BSc Actuarial Science'
        ],
        'management in living':[
            'BSc Biological Science',
            'BSc Food Science and Technology'
        ],
        'food and nuitrition':[
            'BSc Biological Science',
            'BSc Food Science and Technology'
        ],
        governement:['BSc Mathematics',
        'BSc Statistics',
        'BSc Actuarial Science',
        ],
        geography:['BSc Mathematics',
        'BSc Statistics',
        'BSc Actuarial Science',
        ],
        'gka(general knowledge in arts)':['BSc Mathematics',
        'BSc Statistics',
        'BSc Actuarial Science',
        ],
    };
    healthandalliedsciences={
        biology:[
            'BSc BDS (Dental Surgery) (Fee-Paying Only)',
            'BSc Disability and Rehabilitation Studies',
            'BSc Human Biology (Medicine)',
            'BSc Medical Laboratory Technology',
            'BSc Midwifery',
            'BSc Nursing',
            'BSc Medical Imaging',
            'Pharm D (Doctor of Pharmacy)',
            'BSc Herbal Medicine',
            'BSc Physician Assistantship',
            'BSc Physiotherapy and Sports Science',
        ],
        physics:[
            'BSc Medical Imaging',
            'BSc Medical Laboratory Technology',
            'BSc Physiotherapy and Sports Science'
        ],
        chemistry:[
            'BSc BDS (Dental Surgery) (Fee-Paying Only)',
            'BSc Disability and Rehabilitation Studies',
            'BSc Human Biology (Medicine)',
            'BSc Medical Laboratory Technology',
            'BSc Midwifery',
            'BSc Nursing',
            'BSc Medical Imaging',
            'Pharm D (Doctor of Pharmacy)',
            'BSc Herbal Medicine',
            'BSc Physician Assistantship',
            'BSc Physiotherapy and Sports Science' 
        ],
        'elective mathematics':[
            'BSc Medical Imaging',
            'BSc Medical Laboratory Technology',
            'BSc Physiotherapy and Sports Science'
 
        ],
        'information technology':[
            'BSc Medical Imaging',
            'BSc Medical Laboratory Technology',
            'BSc Physiotherapy and Sports Science'
        ]

    };
    engineering={
    physics:[
        'BSc Aerospace Engineering',
        'BSc Chemical Engineering',
        'BSc Civil Engineering',
        'BSc Computer Engineering',
        'BSc Geological Engineering',
        'BSc Geomatic (Geodetic) Engineering',
        'BSc Industrial Engineering',
        'BSc Materials Engineering',
        'BSc Mechanical Engineering',
        'BSc Metallurgical Engineering',
        'BSc Petrochemical Engineering',
        'BSc Petroleum Engineering',
        'BSc Telecommunication Engineering',
        'BSc Automobile Engineering',
        'BSc Electrical/Electronic Engineering',
        'BSc Marine Engineering',
    ],
    chemistry:[
        'BSc Petrochemical Engineering',
        'BSc Petroleum Engineering',
        'BSc Chemical Engineering',
        'BSc Agricultural Engineering',
        'BSc Biomedical Engineering',
        'BSc Civil Engineering',
        'BSc Geological Engineering',
        'BSc Geomatic (Geodetic) Engineering',
        'BSc Industrial Engineering',
        'BSc Materials Engineering',
        'BSc Metallurgical Engineering',
        'BSc Marine Engineering',
    ],
    'elective mathematics':[
        'BSc Civil Engineering',
        'BSc Aerospace Engineering',
        'BSc Computer Engineering',
        'BSc Geological Engineering',
        'BSc Geomatic (Geodetic) Engineering',
        'BSc Industrial Engineering',
        'BSc Materials Engineering',
        'BSc Mechanical Engineering',
        'BSc Metallurgical Engineering',
        'BSc Petrochemical Engineering',
        'BSc Petroleum Engineering',
        'BSc Telecommunication Engineering',
        'BSc Automobile Engineering',
        'BSc Electrical/Electronic Engineering',
        'BSc Marine Engineering',
    ],

    biology:[ 'BSc Biomedical Engineering',
              'BSc Agricultural Engineering',
              'BSc Marine Engineering',
              'BSc Geological Engineering',
              'BSc Geomatic (Geodetic) Engineering',
              'BSc Materials Engineering',
              'BSc Marine Engineering',
        ],
    'information technology':[
        'BSc Computer Engineering',
        'BSc Aerospace Engineering',
        'BSc Telecommunication Engineering',
        'BSc Industrial Engineering',
        'BSc Materials Engineering',
        'BSc Electrical/Electronic Engineering',
    ]
    };
    agricultureandnaturalresources={
        biology:['BSc Agribusiness Management',
        'BSc Agricultural Biotechnology',
        'BSc Agriculture',
        'BSc Aquaculture and Water Resources Management',
        'BSc Forest Resources Technology',
        'BSc Landscape Design and Management',
        'BSc Natural Resources Management',
        'Bsc. Packaging Technology'
        ],

        physics:[
        'BSc Landscape Design and Management',
        'BSc Agricultural Biotechnology',
        'BSc Forest Resources Technology',
        'Bsc. Packaging Technology'
        ],

        chemistry:[
        'BSc Agribusiness Management',
        'BSc Agricultural Biotechnology',
        'BSc Agriculture',
        'BSc Aquaculture and Water Resources Management',
        'BSc Forest Resources Technology',
        'BSc Landscape Design and Management',
        'BSc Natural Resources Management',
        'Bsc. Packaging Technology'
        ],
        'elective mathematics':[
            'BSc Agribusiness Management',
            'BSc Agricultural Biotechnology',
            'BSc Agriculture',
            'BSc Aquaculture and Water Resources Management',
            'BSc Forest Resources Technology',
            'BSc Landscape Design and Management',
            'BSc Natural Resources Management',
            'Bsc. Packaging Technology'        
        ],
        accounting:[
            'BSc Agribusiness Management',
            'BSc Agricultural Biotechnology',
            'BSc Agriculture',
            'BSc Aquaculture and Water Resources Management',
            'BSc Forest Resources Technology',
            'BSc Landscape Design and Management',
            'BSc Natural Resources Management',
            'Bsc. Packaging Technology'  
        ],
        economics:[
            'BSc Agribusiness Management',
            'BSc Agricultural Biotechnology',
            'BSc Agriculture',
            'BSc Aquaculture and Water Resources Management',
            'BSc Forest Resources Technology',
            'BSc Landscape Design and Management',
            'BSc Natural Resources Management',
            'Bsc. Packaging Technology'
        ],
        costing:[
            'BSc Agribusiness Management',
            'BSc Agricultural Biotechnology',
            'BSc Agriculture',
            'BSc Aquaculture and Water Resources Management',
            'BSc Forest Resources Technology',
            'BSc Landscape Design and Management',
            'BSc Natural Resources Management',
            'Bsc. Packaging Technology'
        ],
        'business management':[
            'BSc Agribusiness Management',
            'BSc Agricultural Biotechnology',
            'BSc Agriculture',
            'BSc Aquaculture and Water Resources Management',
            'BSc Forest Resources Technology',
            'BSc Landscape Design and Management',
            'BSc Natural Resources Management',
            'Bsc. Packaging Technology'
        ],
        'information technology':[
            'Bsc. Packaging Technology',
            'BSc Agribusiness Management',
            'BSc Agricultural Biotechnology',
            'BSc Agriculture',
            'BSc Aquaculture and Water Resources Management',
            'BSc Forest Resources Technology',
            'BSc Landscape Design and Management',
            'BSc Natural Resources Management',
            
        ],
        'animal science':['BSc Agribusiness Management',
        'BSc Agricultural Biotechnology',
        'BSc Agriculture',
        'BSc Aquaculture and Water Resources Management',
        'BSc Forest Resources Technology',
        'BSc Landscape Design and Management',
        'BSc Natural Resources Management',
        'Bsc. Packaging Technology'
    ],

    'crop science':['BSc Agribusiness Management',
        'BSc Agricultural Biotechnology',
        'BSc Agriculture',
        'BSc Aquaculture and Water Resources Management',
        'BSc Forest Resources Technology',
        'BSc Landscape Design and Management',
        'BSc Natural Resources Management',
        'Bsc. Packaging Technology'
    ],
        
         'general agriculture':['BSc Agribusiness Management',
        'BSc Agricultural Biotechnology',
        'BSc Agriculture',
        'BSc Aquaculture and Water Resources Management',
        'BSc Forest Resources Technology',
        'BSc Landscape Design and Management',
        'BSc Natural Resources Management',
        'Bsc. Packaging Technology'
    ],
        governement:[
        'BSc Agribusiness Management',
        'BSc Agriculture',
        'BSc Natural Resources Management',
        'BSc Aquaculture and Water Resources Management',
        'BSc Landscape Design and Management',
        'Bsc. Packaging Technology' 
        ],

        economics:[
            'BSc Agribusiness Management',
            'BSc Agriculture',
            'BSc Natural Resources Management',
            'BSc Aquaculture and Water Resources Management',
            'BSc Landscape Design and Management',
            'Bsc. Packaging Technology' 
        ],
        geography:[
        'BSc Agribusiness Management',
        'BSc Agricultural Biotechnology',
        'BSc Agriculture',
        'BSc Aquaculture and Water Resources Management',
        'BSc Forest Resources Technology',
        'BSc Landscape Design and Management',
        'BSc Natural Resources Management',
        'Bsc. Packaging Technology'
        
        ],
        'gka(general knowledge in arts)':[
            'BSc Agribusiness Management',
            'BSc Agriculture',
            'BSc Natural Resources Management',
            'BSc Aquaculture and Water Resources Management',
            'BSc Landscape Design and Management',
            'Bsc. Packaging Technology' 
        ],
        twi:[ 'BSc Agribusiness Management',
        'BSc Agriculture',
        'BSc Natural Resources Management',
        'BSc Aquaculture and Water Resources Management',
        'BSc Landscape Design and Management',
        'Bsc. Packaging Technology' 
    ],
        french:[ 'BSc Agribusiness Management',
        'BSc Agriculture',
        'BSc Natural Resources Management',
        'BSc Aquaculture and Water Resources Management',
        'BSc Landscape Design and Management',
        'Bsc. Packaging Technology' 
    ],
    'literature':[ 'BSc Agribusiness Management',
        'BSc Agriculture',
        'BSc Natural Resources Management',
        'BSc Aquaculture and Water Resources Management',
        'BSc Landscape Design and Management',
        'Bsc. Packaging Technology' 
    ],
        td:[ 'BSc Agribusiness Management',
        'BSc Agriculture',
        'BSc Natural Resources Management',
        'BSc Aquaculture and Water Resources Management',
        'BSc Landscape Design and Management',
        'BSc Agricultural Biotechnology',
        'BSc Forest Resources Technology',
        'Bsc. Packaging Technology' 
    ],
    'picture making':['Bsc. Packaging Technology'],

    textiles:['Bsc. Packaging Technology'],
    graphics:['Bsc. Packaging Technology'],
    sculpture:['Bsc. Packaging Technology'],
    leather:['Bsc. Packaging Technology']
    }
    artandbuiltenvironment ={
        physics:['BSc Architecture',
        'BSc Construction Technology and Management',
        'BSc Quantity Surveying and Construction Economics',
        'BSc Human Settlement Planning',
        'BSc Land Economy',
        'BSc Real Estate',
        'BSc Ceramics Design Technology',
        'BSc Metalsmithing and Jewellery Technology',
        'BEd. Junior High School Specialism',
        'BA Publishing Studies',    
    ],
    'elective mathematics':[
        'BSc Architecture',
        'BSc Construction Technology and Management',
        'BSc Quantity Surveying and Construction Economics',
        'BSc Human Settlement Planning',
        'BSc Land Economy',
        'BSc Real Estate',
        'BSc Ceramics Design Technology',
        'BSc Metalsmithing and Jewellery Technology',
        'BEd. Junior High School Specialism',
        'BA Publishing Studies',
        ],
        chemistry:[
        'BSc Ceramics Design Technology',
        'BSc Metalsmithing and Jewellery Technology',
        'BSc Textile Design and Technology',
        'BSc Construction Technology and Management',
        'BSc Human Settlement Planning',
        'BSc Land Economy',
        'BSc Quantity Surveying and Construction Economics',
        'BSc Real Estate',
        'BA Communication Design (Graphic Design)',
        'BA Communication Studies',
        'BA Integrated Rural Art and Industry',
        'BFA Painting and Sculpture',
        'BA Publishing Studies',

        ],
        biology:[
            'BSc Real Estate',
            'BSc Human Settlement Planning',
            'BSc Land Economy',
            'BA Communication Design (Graphic Design)',
            'BA Communication Studies',
            'BA Integrated Rural Art and Industry',
            'BFA Painting and Sculpture',
            'BA Publishing Studies',
            'BEd. Junior High School Specialism',

        ],
        'information technology':[
            'BA Publishing Studies',
            'BA Communication Design (Graphic Design)',
            'BSc Real Estate',
            'BEd. Junior High School Specialism',
            'BSc Ceramics Design Technology',
            'BSc Metalsmithing and Jewellery Technology',
            'BA Communication Studies',
            'BA Integrated Rural Art and Industry',

        ],

        governement:[
            'BSc Construction Technology and Management',
            'BSc Human Settlement Planning',
            'BSc Land Economy',
            'BSc Quantity Surveying and Construction Economics',
            'BSc Real Estate',
            'BEd. Junior High School Specialism',
            'BA Communication Design (Graphic Design)',
            'BA Communication Studies',
            'BA Integrated Rural Art and Industry',
            'BFA Painting and Sculpture',
            'BA Publishing Studies',
            'BSc Architecture',
            'BSc Fashion Design',
            'BSc Ceramics Design Technology',
            'BSc Metalsmithing and Jewellery Technology',
            'BSc Textile Design and Technology',

        ],
        economics:['BSc Construction Technology and Management',
        'BSc Human Settlement Planning',
        'BSc Land Economy',
        'BSc Quantity Surveying and Construction Economics',
        'BSc Real Estate',
        'BEd. Junior High School Specialism',
        'BA Communication Design (Graphic Design)',
        'BA Communication Studies',
        'BA Integrated Rural Art and Industry',
        'BFA Painting and Sculpture',
        'BA Publishing Studies',
        'BSc Architecture',
        'BSc Fashion Design',
        'BSc Ceramics Design Technology',
        'BSc Metalsmithing and Jewellery Technology',
        'BSc Textile Design and Technology',
        ],
        geography:['BSc Construction Technology and Management',
        'BSc Human Settlement Planning',
        'BSc Land Economy',
        'BSc Quantity Surveying and Construction Economics',
        'BSc Real Estate',
        'BEd. Junior High School Specialism',
        'BA Communication Design (Graphic Design)',
        'BA Communication Studies',
        'BA Integrated Rural Art and Industry',
        'BFA Painting and Sculpture',
        'BA Publishing Studies',
        'BSc Architecture',
        'BSc Fashion Design',
        'BSc Ceramics Design Technology',
        'BSc Metalsmithing and Jewellery Technology',
        'BSc Textile Design and Technology',
        ],

        'gka(general knowledge in arts)':[
            'BA Communication Design (Graphic Design)',
        'BA Communication Studies',
        'BA Integrated Rural Art and Industry',
      
        'BA Publishing Studies',
        'BEd. Junior High School Specialism',
        'BSc Fashion Design',
       

        ],
        twi:['BA Communication Design (Graphic Design)',
        'BA Communication Studies',
        'BA Integrated Rural Art and Industry', 
        'BA Publishing Studies',
        'BEd. Junior High School Specialism',
        'BSc Fashion Design',
        

        ],
        french:[
            'BA Communication Design (Graphic Design)',
        'BA Communication Studies',
        'BA Integrated Rural Art and Industry',
        
        'BA Publishing Studies',
        'BEd. Junior High School Specialism',
        'BSc Fashion Design',
        

        ],
        'literature':[
            'BA Communication Design (Graphic Design)',
        'BA Communication Studies',
        'BA Integrated Rural Art and Industry',
        'BA Publishing Studies',
        'BEd. Junior High School Specialism',
        'BSc Fashion Design',
       
        ],
        'picture making':['BA Integrated Rural Art and Industry',
        'BFA Painting and Sculpture',
        'BA Publishing Studies',
        'BSc Fashion Design',
        'BSc Ceramics Design Technology',
        'BSc Metalsmithing and Jewellery Technology',
        'BSc Textile Design and Technology',
        'BEd. Junior High School Specialism',
        ],
        textiles:[
        'BSc Textile Design and Technology',
        'BA Integrated Rural Art and Industry',
        'BFA Painting and Sculpture',
        'BA Publishing Studies',
        'BSc Fashion Design',
        'BSc Ceramics Design Technology',
        'BSc Metalsmithing and Jewellery Technology',
        'BEd. Junior High School Specialism',
        ],
        graphics:[
            'BA Communication Design (Graphic Design)',
            'BA Communication Studies',
            'BA Integrated Rural Art and Industry',
            'BFA Painting and Sculpture',
            'BA Publishing Studies',
            'BSc Fashion Design',
            'BSc Ceramics Design Technology',
            'BSc Metalsmithing and Jewellery Technology',
            'BSc Textile Design and Technology',
            'BEd. Junior High School Specialism',
        ],
        leather:['BA Integrated Rural Art and Industry',
        'BFA Painting and Sculpture',
        'BA Publishing Studies',
        'BSc Fashion Design',
        'BSc Ceramics Design Technology',
        'BSc Metalsmithing and Jewellery Technology',
        'BSc Textile Design and Technology',
        'BEd. Junior High School Specialism',
        ],
        sculpture:['BA Integrated Rural Art and Industry',
        'BFA Painting and Sculpture',
        'BA Publishing Studies',
        'BSc Fashion Design',
        'BSc Ceramics Design Technology',
        'BSc Metalsmithing and Jewellery Technology',
        'BSc Textile Design and Technology',
        'BEd. Junior High School Specialism',
        ],

        'building construction':[
            'BSc Architecture',
            'BSc Construction Technology and Management',
            'BSc Land Economy',
            'BSc Quantity Surveying and Construction Economics',
            'BSc Real Estate',
            'BSc Human Settlement Planning',
            'BEd. Junior High School Specialism',
            'BSc Metalsmithing and Jewellery Technology',
            'BSc Textile Design and Technology',
            'BSc Fashion Design',
            'BSc Ceramics Design Technology',
            'BA Publishing Studies',

        ],
        wood:[
            'BSc Land Economy',
            'BSc Quantity Surveying and Construction Economics',
            'BSc Real Estate',
            'BA Communication Design (Graphic Design)',
            'BA Communication Studies',
            'BA Integrated Rural Art and Industry',
            'BFA Painting and Sculpture',
            'BA Publishing Studies',

        ],
        'technical drawing':[
            'BSc Architecture',
            'BSc Construction Technology and Management',
            'BSc Land Economy',
            'BSc Quantity Surveying and Construction Economics',
            'BSc Real Estate',
            'BSc Human Settlement Planning',
            'BEd. Junior High School Specialism',
            'BSc Metalsmithing and Jewellery Technology',
            'BSc Textile Design and Technology',
            'BSc Fashion Design',
            'BSc Ceramics Design Technology',
            'BA Publishing Studies',

        ]
    }
    humanitiesandsocialsciences={
      biology:[
        'BSc Hospitality and Tourism Management',
        'LLB',
        'BA Religious Studies',
        'BA Sociology',
        'BA Social Work',
        'BSc Development Planning',
        'BA Akan Language and Culture',
        'BA Culture and Tourism',
        'BA Economics',
        'BA English',
        'BSc Business Administration (Logistics and Supply Chain Mgt/Bus. Info. Tech.)',
        'BSc Business Administration ((Human Resource Management/Management)',
      ],
     physics:['BA Geography and Rural Development',
         'BA History',
         'BA Political Studies',
         'BA Religious Studies',
         'BA Sociology',
         'BA Social Work',
         'BSc Development Planning',
        'BSc Business Administration ((Human Resource Management/Management)',
        'BSc Business Administration (Marketing/International Business)',
        'BSc Business Administration (Accounting/Banking and Finance)',
        'BSc Business Administration (Logistics and Supply Chain Mgt/Bus. Info. Tech.)',
        'BSc Hospitality and Tourism Management',
        'LLB',
     ],
     'elective mathematics':[
        'BA Economics',
        'BSc Business Administration ((Human Resource Management/Management)',
        'BSc Business Administration (Marketing/International Business)',
        'BSc Business Administration (Accounting/Banking and Finance)',
        'BSc Business Administration (Logistics and Supply Chain Mgt/Bus. Info. Tech.)',
        'BSc Hospitality and Tourism Management',
        'LLB',
        'BA Sociology',
        'BA Social Work',
        'BSc Development Planning',
        'BA Economics',
        'BA Geography and Rural Development',
     ],
     chemistry:[
      'BA Geography and Rural Development',
      'LLB',
     'BA History',
     'BA Political Studies',
     'BA Religious Studies',
     'BA Sociology',
     'BA Social Work',
     'BSc Development Planning',
    'BSc Business Administration ((Human Resource Management/Management)',
    'BSc Business Administration (Marketing/International Business)',
    'BSc Business Administration (Accounting/Banking and Finance)',
    'BSc Business Administration (Logistics and Supply Chain Mgt/Bus. Info. Tech.)',
    'BSc Hospitality and Tourism Management',
     ],
     'information technology':[
        'BA Economics',
        'BSc Development Planning',
        'BA Linguistics',
        'BSc Business Administration ((Human Resource Management/Management)',
        'BSc Business Administration (Marketing/International Business)',
        'BSc Business Administration (Accounting/Banking and Finance)',
        'BSc Business Administration (Logistics and Supply Chain Mgt/Bus. Info. Tech.)',
        'BSc Hospitality and Tourism Management',
     ],
     accounting:[ 'BSc Business Administration (Accounting/Banking and Finance)',
        'BSc Business Administration ((Human Resource Management/Management)',
        'BSc Business Administration (Marketing/International Business)',
        'BSc Business Administration (Logistics and Supply Chain Mgt/Bus. Info. Tech.)',
        'BSc Hospitality and Tourism Management',
        'LLB',
        'BSc Development Planning',
        'BA Geography and Rural Development',
        'BA History',
        'BA Political Studies',
        'BA Religious Studies',
        'BA Sociology',
        'BA Social Work',
       
        
        
     ],
     economics:[
        'BSc Business Administration ((Human Resource Management/Management)',
     'BSc Business Administration (Marketing/International Business)',
     'BSc Business Administration (Logistics and Supply Chain Mgt/Bus. Info. Tech.)',
     'BSc Hospitality and Tourism Management',
      'BSc Business Administration (Accounting/Banking and Finance)',
     'LLB',
     'BSc Development Planning',
     'BA Geography and Rural Development',
     'BA History',
     'BA Political Studies',
     'BA Religious Studies',
     'BA Sociology',
     'BA Social Work',
     ],
     'business management':[  'BSc Business Administration ((Human Resource Management/Management)',
     'BSc Business Administration (Marketing/International Business)',
     'BSc Business Administration (Logistics and Supply Chain Mgt/Bus. Info. Tech.)',
     'BSc Hospitality and Tourism Management',
      'BSc Business Administration (Accounting/Banking and Finance)',
     'LLB',
     'BSc Development Planning',
     'BA Geography and Rural Development',
     'BA History',
     'BA Political Studies',
     'BA Religious Studies',
     'BA Sociology',
     'BA Social Work',
     ],
     costing:[  'BSc Business Administration ((Human Resource Management/Management)',
     'BSc Business Administration (Marketing/International Business)',
     'BSc Business Administration (Logistics and Supply Chain Mgt/Bus. Info. Tech.)',
     'BSc Hospitality and Tourism Management',
      'BSc Business Administration (Accounting/Banking and Finance)',
     'LLB',
     'BSc Development Planning',
     'BA Geography and Rural Development',
     'BA History',
     'BA Political Studies',
     'BA Religious Studies',
     
     'BA Sociology',
     'BA Social Work',

     ],
     governement:[
        'LLB',
        'BA Geography and Rural Development',
        'BA History',
        'BA Political Studies',
        'BSc Business Administration ((Human Resource Management/Management)',
        'BSc Business Administration (Marketing/International Business)',
        'BSc Business Administration (Accounting/Banking and Finance)',
        'BSc Business Administration (Logistics and Supply Chain Mgt/Bus. Info. Tech.)',
        'BA Religious Studies',
        'BA Sociology',
        'BA Social Work',
        'BSc Development Planning',
        'BA Akan Language and Culture',
        'BSc Hospitality and Tourism Management',
        'BA Culture and Tourism',
        'BA Economics',
        'BA English',
        'BA French and Francophone Studies',  
     ],
     geography:[
        'LLB',
        'BA Geography and Rural Development',
        'BSc Business Administration ((Human Resource Management/Management)',
        'BSc Business Administration (Marketing/International Business)',
        'BSc Business Administration (Accounting/Banking and Finance)',
        'BSc Business Administration (Logistics and Supply Chain Mgt/Bus. Info. Tech.)',
        'BA History',
        'BA Political Studies',
        'BA Religious Studies',
        'BA Sociology',
        'BSc Hospitality and Tourism Management',
        'BA Social Work',
        'BSc Development Planning',
        'BA Akan Language and Culture',
        'BA Culture and Tourism',
        'BA Economics',
        'BA English',
        'BA French and Francophone Studies',
     ],
     'gka(general knowledge in arts)':[
        'BA Linguistics',
        'BSc Hospitality and Tourism Management',
        'BA Akan Language and Culture',
        'BA Culture and Tourism',
        'BA Economics',
        'BA English',
        'BA French and Francophone Studies',
        'BA Geography and Rural Development',
        'BA History',
        'BA Political Studies',
        'BA Religious Studies',
        'BA Sociology',
        'BA Social Work',
        'BSc Development Planning',
     ],
     twi:['BA Akan Language and Culture',
     'BA Culture and Tourism',
     'BA English',
     'BA French and Francophone Studies',
     'BA History',
     'BA Sociology',
     'BA Social Work',
     'BA Linguistics',
     ],
     french:[
        'BA Akan Language and Culture',
     'BA Culture and Tourism',
     'BA English',
     'BA French and Francophone Studies',
     'BA History',
     'BA Sociology',
     'BA Social Work',
     'BA Linguistics',
     ],
     'literature':[
    'LLB',
    'BA Akan Language and Culture',
     'BA Culture and Tourism',
     'BA English',
     'BA French and Francophone Studies',
     'BA History',
     'BA Sociology',
     'BA Social Work',
     'BA Linguistics',
     ],
     'management in living':[
        'BA Sociology',
        'BA Social Work',
        'BSc Development Planning',
        'BA Linguistics',
        'BA Akan Language and Culture',
        'BA Culture and Tourism',
        'BA History',
        'BA Political Studies',
        'BA Religious Studies',
     ],
     'food and nuitrition':[
        'BA Sociology',
        'BA Social Work',
        'BSc Development Planning',
        'BA Linguistics',
        'BA Akan Language and Culture',
        'BA Culture and Tourism',
        'BA History',
        'BA Political Studies',
        'BA Religious Studies',
     ],
     'clothing and textiles':[
        'BA Social Work',
        'BSc Development Planning',
        'BA Linguistics',
        'BA Akan Language and Culture',
        'BA Culture and Tourism',
        'BA History',
        'BA Religious Studies',
     ],
     'picture making':[
        'BA Social Work',
        'BSc Development Planning',
        'BA Linguistics',
        'BA Akan Language and Culture',
        'BA Culture and Tourism',
        'BA History',
        'BA Religious Studies',
     ],
     graphics:[
        'BA Social Work',
        'BSc Development Planning',
        'BA Linguistics',
        'BA Akan Language and Culture',
        'BA Culture and Tourism',
        'BA History',
        'BA Religious Studies',
     ],
     sculpture:[
        'BA Social Work',
        'BSc Development Planning',
        'BA Linguistics',
        'BA Akan Language and Culture',
        'BA Culture and Tourism',
        'BA History',
        'BA Religious Studies',
     ],
     leather:[
        'BA Social Work',
        'BSc Development Planning',
        'BA Linguistics',
        'BA Akan Language and Culture',
        'BA Culture and Tourism',
        'BA History',
        'BA Religious Studies',
     ],
     wood:[
        'BSc Development Planning',
        'BA Social Work',
        'BA Linguistics',
        'BA Akan Language and Culture',
        'BA Culture and Tourism',
        'BA History',
        'BA Religious Studies',
     ],
     'building construction':[
        'BSc Development Planning',
        'BA Geography and Rural Development',
        'BSc Hospitality and Tourism Management',
        'BA Culture and Tourism',
        'BA Economics',
        'BA History',
        'BA Political Studies',
        'BA Religious Studies',
        'BA Sociology',
        'BA Social Work',
        'BA Linguistics',
     ],
     'general agriculture':['BA History',
     'BA Social Work',
     'BA Linguistics',
     'BA Akan Language and Culture',
     'BA Culture and Tourism',

     ],
     'crop science':['BA History',
     'BA Social Work',
     'BA Linguistics',
     'BA Akan Language and Culture',
     'BA Culture and Tourism',],
     'animal science':['BA History',
     'BA Social Work',
     'BA Linguistics',
     'BA Akan Language and Culture',
     'BA Culture and Tourism',]
    }
    
}

 module.exports = Labeller;