

('BA Akan Language and Culture, 6, 24'),
('BA Communication Design (Graphic Design), 5, 14'),
('BA Communication Studies, 5, 12'),
('BA Culture and Tourism, 6, 16'),
('BA Economics, 6, 13'),
('BA English, 6, 20'),
('BA French and Francophone Studies, 6, 15'),
('BA Geography and Rural Development, 6, 14'),
('BA History, 6, 18'),
('BA Integrated Rural Art and Industry, 5, 19'),
('BFA Painting and Sculpture, 5, 20'),
('BA Political Studies, 6, 11'),
('BA Publishing Studies, 5, 16'),
('BA Religious Studies, 6, 24'),
('BA Sociology, 6, 14'),
('BA Social Work, 6, 15'),
('BSc Actuarial Science, 2, 11'),
('BSc Aerospace Engineering, 3, 9'),
('BSc Agribusiness Management, 4, 18'),
('BSc Agricultural Biotechnology, 4, 19'),
('BSc Agricultural Engineering, 3, 16'),
('BSc Agriculture, 4, 24'),
('BSc Aquaculture and Water Resources Management, 4, 24'),
('BSc Architecture, 5, 9'),
('BSc BDS (Dental Surgery) (Fee-Paying Only), 1, 8'),
('BSc Biochemistry, 2, 10'),
('BSc Biological Science, 2, 12'),
('BSc Biomedical Engineering, 3, 7'),
('BSc Chemical Engineering, 3, 10'),
('BSc Chemistry, 2, 18'),
('BSc Civil Engineering, 3, 10'),
('BSc Computer Engineering, 3, 9'),
('BSc Computer Science, 3, 11'),
('BSc Construction Technology and Management, 5, 14'),
('BSc Development Planning, 6, 12'),
('BSc Disability and Rehabilitation Studies, 1, 17'),
('BSc Environmental Sciences, 2, 17'),
('BSc Food Science and Technology, 2, 14'),
('BSc Forest Resources Technology, 4, 24'),
('BSc Geological Engineering, 3, 13'),
('BSc Geomatic (Geodetic) Engineering, 3, 14'),
('BSc Human Biology (Medicine), 5, 6'),
('BSc Human Settlement Planning, 5, 16'),
('BSc Industrial Engineering, 3, 15'),
('BSc Land Economy, 5, 9'),
('BSc Landscape Design and Management, 4, 22'),
('BSc Materials Engineering, 3, 14'),
('BSc Mechanical Engineering, 3, 10'),
('BSc Medical Laboratory Technology, 1, 8'),
('BSc Metallurgical Engineering, 3, 16'),
('BSc Meteorology and Climate Science, 2, 21'),
('BSc Midwifery, 1, 10'),
('BSc Natural Resources Management, 4, 20'),
('BSc Nursing, 1, 9'),
('BSc Petrochemical Engineering, 3, 9'),
('BSc Petroleum Engineering, 3, 7'),
('BSc Physics, 2, 21'),
('BSc Quantity Surveying and Construction Economics, 5, 14'),
('BSc Real Estate, 5, 13'),
('BSc Medical Imaging, 1, 10'),
('BSc Statistics, 2, 16'),
('BSc Telecommunication Engineering, 3, 11'),
('Doctor of Optometry, 2, 6'),
('(DVM) Doctor of Veterinary Medicine, 2, 15'),
('Pharm D (Doctor of Pharmacy), 1, 6'),
('BEd. Junior High School Specialism, 5, 24'),
('BA Linguistics, 6, 22'),
('BSc Fashion Design, 5, 16'),
('BSc Ceramics Design Technology, 5, 24'),
('BSc Metalsmithing and Jewellery Technology, 5, 24'),
('BSc Textile Design and Technology, 5, 18'),
('BSc Automobile Engineering, 3, 14'),
('BSc Business Administration ((Human Resource Management/Management), 6, 10'),
('BSc Business Administration (Marketing/International Business), 6, 12'),
('BSc Business Administration (Accounting/Banking and Finance), 6, 9'),
('BSc Business Administration (Logistics and Supply Chain Mgt/Bus. Info. Tech.), 6, 12'),
('BSc Hospitality and Tourism Management, 6, 13'),
('BSc Electrical/Electronic Engineering, 3, 7'),
('BSc Herbal Medicine, 1, 16'),
('BSc Marine Engineering, 3, 12'),
('BSc Mathematics, 2, 18'),
('BSc Physician Assistantship, 1, 7'),
('BSc Physiotherapy and Sports Science, 1, 14'),
('LLB, 6, 6')
